### ISSUE TITLE
Bug: Only emailid being synced

### ISSUE THREAD

**Issue by sukeshak** [nopSolutions/sendinblue-plugin-for-nopcommerce#1]
First of all, thank you for the plugin. Its great to have this feature part of nopCommerce.

Now the issue:
The sync only synchronizes email id and not the name, full name etc...
Please look into this.

Using 3.8 version

**Comment by RomanovM** [comment]
Resolved in https://github.com/nopSolutions/sendinblue-plugin-for-nopcommerce/commit/1870f07ce5631e0457a3a8014183141956f7042b
