### ISSUE TITLE
Send partner name

### ISSUE THREAD

**Issue by skoshelev** [nopSolutions/sendinblue-plugin-for-nopcommerce#2]
... Unfortunately, I cannot recoup this with our active and paying customers. Is it possible to share the list of the websites who downloaded it ? (just the domain name would do, so I could be able to recoup this info with our active customers).

So that we could track next plugin installs, could you please forward the screenshot attached to someone from your dev team? 
The API v2 documentation can be found on https://apidocs.sendinblue.com/fr/

@RomanovM ditails in slack: developer 17.07.2018 11:51

**Comment by RomanovM** [comment]
Resolved in https://github.com/nopSolutions/sendinblue-plugin-for-nopcommerce/commit/cc428ef140fc404bbdcfd6aac2226fbd6de7d406
