### ISSUE TITLE
Sendinblue plugin not working

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/sendinblue-plugin-for-nopcommerce#3]
Source https://www.nopcommerce.com/boards/t/56087/sendinblue-plugin-not-working-out-the-box.aspx

**Comment by skoshelev** [comment]
Closed #3(https://github.com/nopSolutions/sendinblue-plugin-for-nopcommerce/commit/d4e6883296ad8969315d8f35efeb76fe336159f8)
